# Generated by Django 5.0.6 on 2024-08-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_product_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='decription',
        ),
    ]
