# Generated by Django 5.0.6 on 2024-08-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_catagory_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
