# Generated by Django 5.1 on 2024-08-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_catagory_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/femily'),
        ),
    ]
